title: Z Aufgespritzer glog powered !blog.
email: h.nedim@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ich bin ein Aufgespritzter.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hadzimahmutovic.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  neidiom

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
